Repository ActoKids/devops, pull requests merged in 2019-03, with the labels that each got.

#27 Ad440 w19 Prod and Dev document policies
  scripts/iam/prod-dev-policies/README.md
  scripts/iam/prod-dev-policies/dev/dev-pol-1.json
  scripts/iam/prod-dev-policies/dev/dev-pol-2.json
  scripts/iam/prod-dev-policies/dev/dev-pol-3.json
  scripts/iam/prod-dev-policies/dev/dev-pol-4.json
  scripts/iam/prod-dev-policies/prod/prod-pol-1.json
  scripts/iam/prod-dev-policies/prod/prod-pol-2.json
  scripts/iam/prod-dev-policies/prod/prod-pol-3.json
  scripts/iam/prod-dev-policies/prod/prod-pol-4.json
Labels: DevOps team

#38 Adding the scripts for Sprint 4
  scripts/apigw dev/POST.js
  scripts/apigw dev/README.md
  scripts/apigw dev/Sprint4_DEV.tf
  scripts/apigw dev/index.js
  scripts/apigw dev/lambda.zip
  scripts/apigw dev/lambda_POST.zip
  scripts/apigw dev/policies/lambda-role.json
  scripts/apigw dev/variables.tf
Labels: DevOps team, Sprint 4

#40 Feature/ui prod automation
  automation/ui-prod-endpoint-automation/create-distribution-cloudfront.json
  automation/ui-prod-endpoint-automation/ui-s3-prod-automation.bat
  automation/ui-prod-endpoint-automation/ui-s3-prod-automation.sh
  automation/ui-prod-endpoint-automation/upsert-record-r53.json
Labels: Sprint 4

#43 added automation script for dev ui
  scripts/ui-endpoints-automation-dev/s3-endpoint-dev-automation.sh
Labels: Sprint 4

#24 Lambda Terraform with Parameters, Environment and Tags
  scripts/lambdaterraform/lambda.tf
  scripts/lambdaterraform/readme.txt
  scripts/lambdaterraform/variables.tf
Labels: Sprint 4

#54 Ad440 w19 ui 1box terraform anar
  automation/ui-1box-endpoint-automation/1box.tf
Labels: Sprint 4
